### ISSUE TITLE
Future never gets completed if no deferred deep link [Android]

### ISSUE THREAD

**Issue by mayurdhurpate** [Mapk26/flutter_facebook_app_links#1]
Great plugin!

I'm facing an issue that if the app has no deferred deep links or if the `initFBLinks` has already been called one, the Future `initFBLinks` doesn't complete. It would be great if the plugin can throw an error/return null/blank values in those cases.

I believe it could be related to the empty else clause:
https://github.com/Mapk26/flutter_facebook_app_links/blob/316c35027608ff37f861f7d968d81533661c25af/android/src/main/java/it/remedia/flutter_facebook_app_links/FlutterFacebookAppLinksPlugin.java#L96

**Comment by Mapk26** [comment]
@mayurdhurpate , thanks for this report (affecting Android only).

I am going to fix it returning null in case a deferred deep link is not returned from FB.

**Comment by Mapk26** [comment]
The issue has been fixed in version 1.0.2

**Comment by KelryAFernandes** [comment]
Hello, can you help me? For some reason the method always returns null, "await _channel.invokeMethod ('initFBLinks')", can this be a problem with the deeplink creation pattern? the code is all according to yours, the id according to the one on the facebook app, I can't find a reason to always return null.
