### ISSUE TITLE
error: type 'Settings' has no member 'isAutoInitEnabled'

### ISSUE THREAD

**Issue by hakivin** [Mapk26/flutter_facebook_app_links#12]
i have problem when build app for iOS
return this
```
SwiftFlutterFacebookAppLinksPlugin.swift:15:14: error: type 'Settings' has no member 'isAutoInitEnabled'
Settings.isAutoInitEnabled = true
```
i've set deployment target to 10.0
how to resolve this error?
thanks

**Comment by Mapk26** [comment]
Hi,
please try the new version with null safety:

`flutter_facebook_app_links: ^2.0.0+2`

**Comment by hakivin** [comment]
my project currently use flutter 1, any other solution?

**Comment by Mapk26** [comment]
FBSDKCoreKit updated to 14.1.0

It needs Flutter >=2.2.1
