### ISSUE TITLE
'flutter_facebook_app_links/ios/Classes/SwiftFlutterFacebookAppLinksPlugin.swift' file not found

### ISSUE THREAD

**Issue by affparty** [Mapk26/flutter_facebook_app_links#13]
Hi, i am having issue with ios build. 
To reproduce
- create Flutter app
- add   flutter_facebook_app_links: ^2.0.0+2 to pubspec.yaml
- try to run app in ios simulator

I got this error: 'flutter_facebook_app_links/ios/Classes/SwiftFlutterFacebookAppLinksPlugin.swift' file not found

**Comment by Mapk26** [comment]
Hi the plugin has been updated and FBSDKCoreKit bump to 14.1.0
