### ISSUE TITLE
Update FBSDKCoreKit version

### ISSUE THREAD

**Issue by chamartt** [Mapk26/flutter_facebook_app_links#15]
Hi,

I have conflict with another plugin which uses FBSDKCoreKit (~> 12.1.0), could you please update your plugin in order to use the same FBSDKCoreKit version ?

Thank you in advance !

**Comment by imedboumalek** [comment]
this should be fixed in the latest PR, waiting on the maintainer to update pub.dev package (see #19 ). In the meantime, cloning the package into the project and having the pubspec.yaml file manually route to it is a good workaround.

**Comment by Mapk26** [comment]
FBSDKCoreKit updated to 14.1.0
