### ISSUE TITLE
Facebook deferred deep link is not working on latest version of flutter_facebook_app_links  in ios

### ISSUE THREAD

**Issue by imofidul** [Mapk26/flutter_facebook_app_links#20]
In latest version facebook ads deeplink is empty 

 ```
deepLinkUrl = await FlutterFacebookAppLinks.initFBLinks();
    if(Platform.isIOS)
      deepLinkUrl = await FlutterFacebookAppLinks.getDeepLink();
```
Here deeplinkUrl is empty always in latest version `flutter_facebook_app_links: ^3.0.0+5` on ios

**Comment by Mapk26** [comment]
Check if in your info.plist you have the Facebook Client Token that is currently missing inside the doc.

`
<key>FacebookAppID</key>`
`<string>YOUR_APP_ID</string>`
`<key>FacebookClientToken</key>`
`<string>YOUR_CLIENT_TOKEN</string>
`

**Comment by mrinaljain** [comment]
I am also facing the same problem with my iOS build.
just checked my info.plist file and it contains FacebookAppID as well as FacebookClientToken.

**Comment by mrinaljain** [comment]
@Mapk26   any updates on this?

**Comment by JHaooooo** [comment]
[flutter_facebook_app_links](https://github.com/Mapk26/flutter_facebook_app_links)/[ios](https://github.com/Mapk26/flutter_facebook_app_links/tree/master/ios)/[Classes](https://github.com/Mapk26/flutter_facebook_app_links/tree/master/ios/Classes)/SwiftFlutterFacebookAppLinksPlugin.swift


Add a line of code after `registrar.addMethodCallDelegate(instance, channel: channel)`

`registrar.addApplicationDelegate(instance)`
