### ISSUE TITLE
FBSDKCoreKit  14.1.0- -> 15.1 Please request an update

### ISSUE THREAD

**Issue by shinyul** [Mapk26/flutter_facebook_app_links#21]
FBSDKCoreKit  14.1.0- -> 15.1 Please request an update
I want to use it with facebook_app_events, but the version doesn't match

facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 15.1)

    flutter_facebook_app_links (from `.symlinks/plugins/flutter_facebook_app_links/ios`) was resolved to 3.0.0, which depends on
      FBSDKCoreKit (~> 14.1.0)

**Comment by Mapk26** [comment]
Published v3.0.1+6
