### ISSUE TITLE
FacebookSdk.sdkInitialize() not been initialized

### ISSUE THREAD

**Issue by patoliavishal** [Mapk26/flutter_facebook_app_links#24]
The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

this error appears while running the Android build.

**Comment by patoliavishal** [comment]
After following the perfect step error is not visible

**Comment by webtamizhan** [comment]
What is "Perfect step" you have followed?

Me too facing this issue. Please guide us.

**Comment by SourcCode-eg** [comment]
i am faceing the same issue here can you share with us what changes have you done to make it work with you
