### ISSUE TITLE
app link always returns null

### ISSUE THREAD

**Issue by KamranKhan-QH** [Mapk26/flutter_facebook_app_links#28]
Hi!,

I am implementing deferred deep link in my Flutter app. I have checked all the configurations more than five times, and I spend more than 3 days implementing this.. but it always returns null. Kindly help me I don't know what am I missing.

thanks

**Comment by KamranKhan-QH** [comment]
had to reset advertisement id of my phone then its started working.

**Comment by iamtechieboy** [comment]
@KamranKhan-QH Could you write what did you exactly. I am facing same issue of not getting links in first launch. Is this service working still. or do i need to switch to services line brach.io and adjust.

**Comment by kamran8545** [comment]
navigate to Device Settings > Privacy > Ads > Reset Advertising ID. and test again, Make sure you are testing using FB Dev Testing tool, then you will be able to receive the link. Let me know if you have any other questions.

**Comment by iamtechieboy** [comment]
@kamran8545 Thank you for your response. But i cannot find "Reset Advertising ID" in my device. I have both android and ios device to test. Or did I do it wrong. And another question is this service, i mean facebook deferred link is still working ??.

I cannot handle any first launch links. I have been trying for a week. Can you help me closely ?

**Comment by KamranKhan-QH** [comment]
I am not using FB deferred link.. but let me check it once if they are still working or not.
