### ISSUE TITLE
Issues with FBSDK v5

### ISSUE THREAD

**Issue by algirdasmac** [Mapk26/flutter_facebook_app_links#3]
This plugin uses FBSDK v5 and Apple is deprecating UIWebView (which v5 uses). So if we want our apps in AppStore - we need to move to a newer version - v7.

In my case, I use flutter_login_facebook 0.2.1 and facebook_app_events 0.7.0 (which uses v7). When I add both of the plugins I get version compatibility errors:
```
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 7.1.0)

        flutter_facebook_app_links (from `.symlinks/plugins/flutter_facebook_app_links/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 5.0)
```

**Comment by chamartt** [comment]
Same for me, did you fix it ?

Thank you !

**Comment by chamartt** [comment]
@Mapk26 did you think there is a conflict between the 2 FBSDCoreKit versions (7.1.0 & 5.1) needed for the both plugins facebook_app_events & flutter_facebook_app_links ?

This issue happens me when I try to add flutter_facebook_app_links plugin ; with only the first one, my builds worked well.
It's just when I try to add the second one, that's why I'm thinking about conflicts between both version of FBSDKCoreKit needed.

I want to say also that I never had to add `pod "FBSDKCoreKit"` in my Podfile.

Do you agree @algirdasmac ?

Thank you for your help.

**Comment by Mapk26** [comment]
Hello @chamartt  and @algirdasmac ,

sorry for the late reply but these are busy days... I had a look (i'm not an iOS expert) and probably I will need to bump this dependency to 7.1

I had no time to test or investigate so if one of you can try, clone this repo and link it in the pubspec, then try to change : 

`s.dependency 'FBSDKCoreKit', '~> 5.0'`

to

`s.dependency 'FBSDKCoreKit', '~> 7.1'`  or whatever

The file is: 
ios/flutter_facebook_app_links.podspec

If it works I will fix it and push ASAP.
Thanks in advance and apologize for this delay.

**Comment by chamartt** [comment]
Ok I try it now !

Thanks for the reply.

**Comment by chamartt** [comment]
@Mapk26 the `pod install` step worked well with your fix !
The `XCode running build` is in progress but I think it will be good.

Thanks a lot for your help.

**Comment by algirdasmac** [comment]
> Hello @chamartt and @algirdasmac ,
> 
> sorry for the late reply but these are busy days... I had a look (i'm not an iOS expert) and probably I will need to bump this dependency to 7.1
> 
> I had no time to test or investigate so if one of you can try, clone this repo and link it in the pubspec, then try to change :
> 
> `s.dependency 'FBSDKCoreKit', '~> 5.0'`
> 
> to
> 
> `s.dependency 'FBSDKCoreKit', '~> 7.1'` or whatever
> 
> The file is:
> ios/flutter_facebook_app_links.podspec
> 
> If it works I will fix it and push ASAP.
> Thanks in advance and apologize for this delay.

I tried this approach - changed to   s.dependency 'FBSDKCoreKit', '~> 7.0'. Published app to appstore and everything seems to work. I guess bumping version is enough.

**Comment by chamartt** [comment]
Hi @Mapk26 !

Did you have push any correction about the issue or do we still need to work with our local fixed project of your plugin ?

Thank you for your answer and your work !

**Comment by Sebubu** [comment]
Same problem here installing `facebook_app_events` with `flutter_facebook_app_links`.

```
    [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 9.0.0)

        flutter_facebook_app_links (from `.symlinks/plugins/flutter_facebook_app_links/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 5.0)
```

Solution was to change 

- `s.dependency 'FBSDKCoreKit', '~> 5.0'`

to

- `s.dependency 'FBSDKCoreKit', '~> 9.0'` 

 in `ios/.symlinks/plugins/flutter_facebook_app_links.podspec`. Let's hope this does not break anything.

**Comment by jjsebastianfuertes** [comment]
any alternative to this plugin?

**Comment by Mapk26** [comment]
@chamartt @Sebubu @jjsebastianfuertes 
The  'FBSDKCoreKit', '~> 9.0' is now updated.

Sorry for the ultra-late reply :)
