### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by jfushada** [Mapk26/flutter_facebook_app_links#7]
Hello, I saw in the documentation that this plugin is used for [Facebook Deep Links](https://developers.facebook.com/docs/app-ads/deep-linking/). Does it work for [Facebook App Links](https://developers.facebook.com/docs/applinks) as well? 

Thanks.

**Comment by Mapk26** [comment]
Hello @jfushada , no this plugin is for deferred deeplinks only.
