### ISSUE TITLE
null safety compability

### ISSUE THREAD

**Issue by chamartt** [Mapk26/flutter_facebook_app_links#9]
Hi Mapk26 !

Do you have news about null safety compability of your plugin ?
We had to update our project and your plugin is our last missing to build completely.

Thank you for your work and your help !

**Comment by Mapk26** [comment]
Hi! 
`flutter_facebook_app_links: ^2.0.0+2`

Sorry for the late reply, the null safety PR has been merged.
Please reopen this issue if something is not working correctly.
